### ISSUE TITLE
zap trash: entries are unquoted strings, brew install fails with syntax errors

### ISSUE THREAD

**Issue by stevehartwell** [appfair/homebrew-app#1]
Looks like an issue with the generation tool that creates these scripts.

Here's an example from fair-skies.rb:
```
zap trash: [
    ~/Library/Application Scripts/app.Fair-Skies,
    ~/Library/Application Support/app.Fair-Skies,
    ~/Library/Caches/app.Fair-Skies,
    ~/Library/Containers/app.Fair-Skies,
    ~/Library/HTTPStorages/app.Fair-Skies,
    ~/Library/HTTPStorages/app.Fair-Skies.binarycookies,
    ~/Library/Preferences/app.Fair-Skies.plist,
    ~/Library/Saved Application State/app.Fair-Skies.savedState
  ]
```

When I edit the `Homebrew/Library/Taps/appfair/homebrew-app/Casks/fair-skies.rb` file to quote the strings, brew install works.

Several (all?) other scripts have the same problem.

**Comment by stevehartwell** [comment]
@marcprux let me know if you need any more info.

**Comment by appfairz** [comment]
This should be fixed by https://github.com/appfair/homebrew-app/commit/072610c560226e8f6607cbdf393bf96611e7cb5b. Please `brew update` and re-open if the issue persists.
